### ISSUE TITLE
equal function problem

### ISSUE THREAD

**Issue by pverkind** [kabikaj/quran_tagger#2]
The equal function has trouble dealing with alifs (e.g., alif+hamza below != alif, alif+waṣla != alif), dagger alifs and sukūns: 

======================================================================
FAIL: test_equal_3_alif_wasla (__main__.TestEqual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\London\OpenITI\tagging\quran\quran_tagger\test_util.py", line 71, in test_equal_3_alif_wasla
    self.assertTrue(equal("ا", "ٱ"))
AssertionError: False is not true

======================================================================
FAIL: test_equal_4_alif_hamza (__main__.TestEqual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\London\OpenITI\tagging\quran\quran_tagger\test_util.py", line 74, in test_equal_4_alif_hamza
    self.assertTrue(equal("ا", "أ"))
AssertionError: False is not true

======================================================================
FAIL: test_equal_5_alif_hamza_below (__main__.TestEqual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\London\OpenITI\tagging\quran\quran_tagger\test_util.py", line 77, in test_equal_5_alif_hamza_below
    self.assertTrue(equal("ا", "إ"))
AssertionError: False is not true

======================================================================
FAIL: test_equal_6_alif_madda (__main__.TestEqual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\London\OpenITI\tagging\quran\quran_tagger\test_util.py", line 80, in test_equal_6_alif_madda
    self.assertTrue(equal("ا", "آ"))
AssertionError: False is not true

======================================================================
FAIL: test_equal_7_dagger_alif (__main__.TestEqual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\London\OpenITI\tagging\quran\quran_tagger\test_util.py", line 83, in test_equal_7_dagger_alif
    self.assertTrue(equal("ما", "مٰا"))
AssertionError: False is not true

======================================================================
FAIL: test_equal_8_sukun (__main__.TestEqual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\London\OpenITI\tagging\quran\quran_tagger\test_util.py", line 86, in test_equal_8_sukun
    self.assertTrue(equal("شيء", "شيْء"))
AssertionError: False is not true

----------------------------------------------------------------------

**Comment by kabikaj** [comment]
The equal function only treats strings after they have passed through normalise, and normalise ignores all alifs and hamzas, this is why. I would try to exclude all alifs from the tagger because:
- in modern script there is sometimes the variation alif-dagger
- in old manuscripts the alif is unstable
- if we later add a module to try to find quran in hebrew or syriac script it might be good not to have to deal with alif too.
but it's my guess
we could also add a flag for treating alifs... I am not sure

**Comment by pverkind** [comment]
Hi Alicia, I agree with your view on the alif. But I think that means that if we feed text to the tagger that includes alifs, the equal function should say the outcome is equal if there is a different alif (or no alif) in the input text, not say they are unequal? Perhaps we are feeding the wrong value to the equal function in the tagger?

**Comment by pverkind** [comment]
(but you're right that my tests don't make sense because we shouldn't pass such raw text to the function)

**Comment by pverkind** [comment]
closing this issue, it seems to be working. Yesterday, I had no results when I turned rasm_match off, so I assumed the problem was with the equalise function, but now it seems to be working even with rasm_match=False, so the problem must have been with something else.

**Comment by kabikaj** [comment]
The expected way to call equal would be equal(normalise("ا"), normalise("ٱ")). In this case, it is just saying that the two strings are equal because they are empty strings after passing normalise, so it is not useful for really comparing alif, but it is synchronised with normalise
